In [12]:
#Course: Data Science Masters
#Title: Python - Assignment 6.1
#Problem Statement: function so that the columns of the output matrix are powers of the input vector.
#      Hint: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.                   
#Tool: Jupyter notebook 
#Author: Krishna A
#Date: 23-2-2018 (DD/MM/YYYY)

import numpy as np
npList = np.array([10,20,30,40])

print("When increasing True")
print(np.vander(npList,increasing=True))  #Using vander static method in numpy library

print("When increasing False")
print(np.vander(npList,increasing=False))  #Using vander static method in numpy library

When increasing True
[[    1    10   100  1000]
 [    1    20   400  8000]
 [    1    30   900 27000]
 [    1    40  1600 64000]]
When increasing False
[[ 1000   100    10     1]
 [ 8000   400    20     1]
 [27000   900    30     1]
 [64000  1600    40     1]]
